Repository coderwassananmol/BUB2, pull requests merged in 2020-03, with the labels that each got.

#48 added footer
  components/Footer.js
Labels: easy, gssoc20

#36 feat: add github star and fork buttons
  components/Header.js
  package.json
Labels: easy, gssoc20

#63 Fixes issue: #39
  CONTRIBUTING.md
Labels: beginner, gssoc20

#69 Changed the name of /queue route to /stats route
  pages/stats.js
Labels: easy, gssoc20

#65 All Panjab typos changed to Punjab
  README.md
Labels: easy, gssoc20

#70 Fixes Issue #58
  LICENSE.md
Labels: easy, gssoc20

#86 Fixed Issue #80(Included Licence Section in README.md)
  README.md
Labels: easy, gssoc20

#83 feat: issue template added
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: easy, gssoc20

#82 Solves issue: #79
  public/Stats Page.fig
Labels: gssoc20, hard

#74 Updated readme with request to contribute section
  README.md
Labels: easy, gssoc20

#84 BUB Logo Added
  README.md
  public/assets/bub2.png
Labels: Design, gssoc20, hard

#71 Fixes Issue Number #52
  ISSUE_TEMPLATE/bug_report.md
  ISSUE_TEMPLATE/feature_request.md
  PR_TEMPLATE.md
Labels: gssoc20, hard

#75 Show number of books uploaded from BUB2 to internet archive
  components/UploadedItems.js
  pages/stats.js
Labels: gssoc20, medium

#89 code of conduct added
  CODE_OF_CONDUCT.md
Labels: beginner, gssoc20

#90 Create GSSOC_INSTRUCTIONS.md
  GSSOC_INSTRUCTIONS.md
Labels: easy, gssoc20

#94 Updated CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: easy, gssoc20

#91 FAQ's added
  FAQ.md
  components/Header.js
Labels: gssoc20, medium

#107 updated stats page UI
  components/Footer.js
  components/ShowQueue.js
  components/UploadedItems.js
  pages/stats.js
Labels: gssoc20, hard

#101 Added queuelisting page
  components/ShowList.js
  pages/queue/list.js
  server.js
  utils/constants.js
Labels: gssoc20, hard

#111 Added pre-commit hooks
  package.json
  server.js
Labels: easy, gssoc20

#116 Add TOC
  README.md
Labels: beginner, gssoc20
